CREATE TABLE IF NOT EXISTS COORDINATES (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y REAL NOT NULL CHECK (y > -976)
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    id SERIAL PRIMARY KEY,
    x BIGINT,
    y BIGINT NOT NULL,
    z DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS ROUTES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL CHECK (trim(name) <> ''),
    coordinates_id INTEGER NOT NULL REFERENCES coordinates(id) ON DELETE RESTRICT,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    from_location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    to_location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    distance REAL CHECK (distance IS NULL OR distance > 1),
    rating DOUBLE PRECISION NOT NULL CHECK (rating > 0)
);

CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS IMPORT_OPERATIONS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('IN_PROGRESS', 'SUCCESS', 'FAILED')),
    imported_count INTEGER,
    error_message VARCHAR(2000),
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP
);
