DROP TABLE IF EXISTS ROUTES CASCADE;
DROP TABLE IF EXISTS COORDINATES CASCADE;
DROP TABLE IF EXISTS LOCATIONS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS IMPORT_OPERATIONS CASCADE;
