DROP TYPE IF EXISTS genders CASCADE;
DROP TYPE IF EXISTS library_status CASCADE;
DROP TYPE IF EXISTS library_card_status CASCADE;
DROP TYPE IF EXISTS booking_status CASCADE;
DROP TYPE IF EXISTS fine_status CASCADE;

DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS readers CASCADE;
DROP TABLE IF EXISTS libraries CASCADE;
DROP TABLE IF EXISTS administrators CASCADE;
DROP TABLE IF EXISTS librarians CASCADE;
DROP TABLE IF EXISTS library_cards CASCADE;
DROP TABLE IF EXISTS materials CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS issuances CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS fines CASCADE;
DROP TABLE IF EXISTS materials_to_libraries CASCADE;
DROP TABLE IF EXISTS materials_to_authors CASCADE;

DROP INDEX IF EXISTS idx_reader_email CASCADE;
DROP INDEX IF EXISTS idx_reader_login CASCADE;
DROP INDEX IF EXISTS idx_addres CASCADE;
DROP INDEX IF EXISTS idx_admin_login CASCADE;
DROP INDEX IF EXISTS idx_librarian_login CASCADE;
