CREATE TABLE IF NOT EXISTS COORDINATES (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y REAL NOT NULL CHECK (y > -976)
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    id SERIAL PRIMARY KEY,
    x BIGINT,
    y BIGINT NOT NULL,
    z DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS ROUTES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL CHECK (trim(name) <> ''),
    coordinates_id INTEGER NOT NULL REFERENCES coordinates(id) ON DELETE RESTRICT,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    from_location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    to_location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE RESTRICT,
    distance REAL CHECK (distance IS NULL OR distance > 1),
    rating DOUBLE PRECISION NOT NULL CHECK (rating > 0)
);
